# Used by inputs-and-outputs/output parameters
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-role
  namespace: ns1
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - create
      - delete
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-patch-binding
  namespace: ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-role
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: ns1
