apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-controller
  name: workflow-controller-metrics
  namespace: ns1
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: workflow-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-workflows
  namespace: ns1
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
      - ns1
  selector:
    matchLabels:
      app: workflow-controller