kind: ConfigMap
apiVersion: v1
metadata: 
  name: app-package-water-bodies-1-0-0
data:
  app-package.json: {{ required "A valid .Values.appPackage entry required!" ( tpl ( .Values.appPackage | default ( .Files.Get "files/app-package.json")) . | quote ) }}